name = "fwti-telemetry"
main = "cloudflare/telemetry-worker.ts"
compatibility_date = "2026-04-11"
account_id = "de7ecb0eaa0a328071255d557a6adb66"
workers_dev = true

[observability]
enabled = true

[[routes]]
pattern = "fwti-telemetry.innei.dev"
custom_domain = true

[[d1_databases]]
binding = "TELEMETRY_DB"
database_name = "fwti-telemetry"
database_id = "f60e3b9d-af12-42cd-ae9e-9a076c9ff12d"
migrations_dir = "cloudflare/migrations"
